name: Run tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradlew_test
        run: ./gradlew test
